### PR TITLE
I think this should do.

### PR DESCRIPTION
**Pull request by nils-a**
I guess @gep13 did a test on that one. 😁 

Let's see if appVeyor is more happy now.

### CODE REVIEW

**Comment by gep13** [comment]
@nils-a not sure if I follow what is going on here?

**Comment by gep13** [comment]
Updating Cake.Json is on my list of ones to go through.  Next on my list is Cake.Incubator, and then I was going to look at Cake.Json.

**Comment by nils-a** [comment]
Sure, no worries. @AdaskoTheBeAsT tried to update Cake.Json but the build is mangeld up - I gess that's the problem.
(And I had the impression you referenced that Cake.Recipe preview - but maybe I'm wrong. Sorry..)

**Comment by gep13** [comment]
@nils-a ah, gotcha.  In all honesty, I am not sure.  Would need to look back in the history of the repo.  Could be I was using this repo as a guinea pig for some changes in Cake.Recipe.

**Comment by nils-a** [comment]
"Someone" did. Cake for the build was set to 1.0.0 and Cake.Recipe to no-longer existing preview.
I started this, comming from https://github.com/cake-contrib/Cake.Json/pull/50#issuecomment-786543151

**Pull request merged**
